// Create our app module...
// IMPORTANT: This setter MUST be called first...
// ...then others can get it via angular.module('app')... 
// NEW: Declare "ngRoute" as a dependency...
var app = angular.module('app', [
	'ngRoute' // Dependency...
]);

